---
language: node_js
node_js:
  - "4.3.2"

sudo: false

cache:
  directories:
    - node_modules

# before_install:
#   - npm config set spin false
#   - npm install -g phantomjs-prebuilt
#   - phantomjs --version

install:
  - npm install

script:
  - npm test

notifications:
  slack: skhazri:UJPXzlZ6vVatyuuHqAwg4W74
